### ISSUE TITLE
Document Upgrade Guide for 0.12.0

### ISSUE THREAD

**Issue by nesquena** [padrino/padrino-framework#1464]
We need to a better job for 0.12.0 of documenting an upgrade guide. Specifically how to upgrade from 0.10.X to 0.12.0 and 0.11.X to 0.12.0 and I want to have this up before we release.

**Comment by igorsantos07** [comment]
@nesquena would someone help me finding the final upgrade guide? The link on this issue is 404, just like a post I found on Twitter: http://padrinorb.com/blog/padrino-0-12-0-activesupport-4-rewritten-reloader-smarter-rendering-and-loads-more

I'm updating an old application and that would be really needed.

**Comment by nesquena** [comment]
@igorsantos07 You can see all available blog posts listed here https://github.com/padrino/padrino-docs/tree/master/blog for easy reference. Looks like maybe that post didn't survive the transition?

**Comment by igorsantos07** [comment]
I guess so, @nesquena! The first post on 0.12 is 0.12.4.

Judging from other frameworks/languages, I think the website should have a dedicated section for upgrades, that would easily list the upgrade path for each major version (i.e. those with breaking changes)... I got really lost looking for those guides around.
