### ISSUE TITLE
Action Cable

### ISSUE THREAD

**Issue by pchaganti** [padrino/padrino-framework#1939]
DHH recently released an alpha(?) version of web sockets for Rails called Action Cable. Not sure yet if this is rails only or will be spun off in a way that other Ruby frameworks can also use it easily. If that is the case, would be great to be able to plug it in to Padrino to get web sockets support.

https://github.com/rails/actioncable

**Comment by nesquena** [comment]
That would definitely be cool, thanks for raising the issue.

**Comment by pchaganti** [comment]
We have been trying to plug other web socket frameworks in to our padrino app. They kinda work, but not there yet. So something like Action cable that we can just plug in would be absolutely cool.Hope you guys will consider this.

thx!

**Comment by dariocravero** [comment]
I put [padrino-websockets](https://github.com/dariocravero/padrino-websockets) a year and something ago and we've been using it in production for ever since without issues. I haven't used ActionCable but it looks kind of similar in functionality as it works with channels identifying users; it does give you a bunch of JS helpers which essentially work as a connection/subscription manager, [here are the basics on padrino-websockets](https://github.com/dariocravero/padrino-websockets/blob/master/examples/padrino-app/app/views/index.slim) and [little chat app that based on both](https://github.com/dariocravero/storyful-messages/blob/master/storyful-messages-app/public/javascripts/application.js#L9-L32). I totally agree that websockets support should make it into Padrino as a first class citizen #1562! :)

**Comment by ujifgc** [comment]
Closing as action-cable probably won't make it to padrino core gems. There might be a place for it in padrino-recipes.
