### ISSUE TITLE
Attribute accessor of new Padrino::PathRouter::Route

### ISSUE THREAD

**Issue by aprikip** [padrino/padrino-framework#2009]
The new `PathRouter` introduced in 0.13.0 have not attribute accessor `:path`.  This attribute accessor is used in `Padrino::Contrib::AutoLocale`, to redirect automatically i18n'ed path.  If there is no security issue about this attribute accessor, I ask to add it.

**Comment by namusyaka** [comment]
@aprikip Thanks for the report! Fixed by [this commit](https://github.com/padrino/padrino-framework/commit/bc3dc2e20205021a1ad3d288f4c281872826b094).
If you're using optional expression, you must append `?` to your route path.
See [this line](https://github.com/padrino/padrino-contrib/blob/978db123fbf6d458914612e41a655c9574490d17/spec/auto_locale_spec.rb#L106).
