### ISSUE TITLE
Release 0.12.6

### ISSUE THREAD

**Issue by namusyaka** [padrino/padrino-framework#2031]

**Comment by sshaw** [comment]
d7d98880ce62bad6fcab946a65648ecdc74e79c9 and 689280ebad11c168883841fa0b7f068fd1c36159 should be added to this release. 

0.12.X has several issues that can prevent one from upgrading from <= 0.11.X (see #2026, #1934, #1794, #1785). All but one (#1785) of these are fixed in 0.13.X. Since there are going to be 0.12 patch releases I see no reason why these shouldn't be added. It will only make folks lives easier.

**Comment by ujifgc** [comment]
d7d9888 and 689280e are now included in 0.12 branch on Github.

**Comment by nesquena** [comment]
Hey all, 

Quick updates:

 * [Compiled changelog for 0.12.6](https://github.com/padrino/padrino-framework/blob/0.12/CHANGES.rdoc#0126)
 * [Draft of the blog post](https://github.com/padrino/padrino-docs/blob/0_13_2_release_drafts/blog/2016-05-08-padrino-0-12-6-backport-and-bug-fixes.md)

@padrino/collaborators can you review / update the changelog and blogpost and/or apply any additional backported fixes we want before release. Make sure all the tests pass, etc. When I get the green light from you, I can push out 0.12.6! Thanks.

**Comment by nesquena** [comment]
Released 0.12.6: [blog post](http://padrinorb.com/blog/padrino-0-12-6-backport-and-bug-fixes/). 🎉
