### ISSUE TITLE
Pry on padrino console

### ISSUE THREAD

**Issue by carlqt** [padrino/padrino-framework#2056]
Hi,
I'm not sure wether to post this here or on pry but here's my problem.
Currently I'm using this technique to convert the standard IRB console of padrino to pry

```
begin
  require 'pry'
  $VERBOSE = nil
  IRB = Pry
  $VERBOSE = false
rescue LoadError
end
```

but with this technique, I'm having trouble with some gems that uses modules/class that's namespaced under `IRB` module, e.g. (IRB::SLex). Any techniques to bypass this?

**Comment by skade** [comment]
This is an incredibly odd way to do this, to be honest. All the console does is load boot and a small file with useful utilities.

https://github.com/padrino/padrino-framework/blob/09d8de672317c9da22c25a01616497852f44f387/padrino-core/lib/padrino-core/cli/base.rb#L26-L41

I used to just call "pry" and then load boot and https://github.com/padrino/padrino-framework/blob/09d8de672317c9da22c25a01616497852f44f387/padrino-core/lib/padrino-core/cli/console.rb

Also, why not submit a patch that allows booting Pry instead of IRB?
