### ISSUE TITLE
Not Found: /   

### ISSUE THREAD

**Issue by federicolucca** [padrino/padrino-framework#2080]
Hi everyone,

just an explanation.
I have two apps on my project with padrino 0.13 .

app --> /api
admin --> /admin

i would like to put a landing page on the root of the domain  

/ --> index.html

how can i do?

thanks
Federico

**Comment by jorgefuertes** [comment]
By default index is routed to your app. Edit the controller and put a "get :index do" block, then render a view, for example "render :index" that view is your index page. 

Of course you can raise more controllers, or apps, and catch that route. 

Enviado desde móvil. Disculpa la brevedad.

El 5 oct. 2016 2:38 p. m., Federico Lucca <notifications@github.com> escribió:

Hi everyone,

just an explanation.
I have two apps on my project with padrino 0.13 .

app --> /api
admin --> /admin

i would like to put a landing page on the root of the domain 

/ --> index.html

how can i do?

thanks
Federico

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread. 

--- Control SPAM: Click here to mark email as junk.
