### ISSUE TITLE
Default content type for mailer incorrect

### ISSUE THREAD

**Issue by simonhambly** [padrino/padrino-framework#575]
Hi,

Just been having some trouble with the mailer and sending multipart emails to gmail. If you configure the email as described in the "mailer guide" like so

```
email :email_notification do
    ...
    provides :plain, :html
    render 'notifier/new_notification_email'
end
```

the default content type is "multipart/mixed" not "multipart/alternative" as the guide incorrectly states.

Having "multipart/mixed" causes gmail to display both the plain and html versions of the email. Changing the email config as below (adding content_type)

```
email :email_notification do
    ...
    content_type 'multipart/alternative'
    provides :plain, :html
    render 'notifier/new_notification_email'
end
```

ensure the email is displayed correclty

**Comment by jorgefuertes** [comment]
I don't know if is possible to reopen this one... now some MUAs, and over some MTAs, shows only the last part, for example an attachement. No text content and no html content, because all are multipart/alternative, suggesting each part is just an alternate view of the same message.

I've tried to workaround it, but no results.

**Comment by ujifgc** [comment]
This looks like `mail` gem problem: https://github.com/mikel/mail/issues/522

I don't think it's related to the original issue.

**Comment by jorgefuertes** [comment]
I'll take a look but in my case the problem is with pdf attachments too. I think you are right and is a mail gem problem. Thank you very much, @ujifgc.
