### ISSUE TITLE
Account changing only password not possible 

### ISSUE THREAD

**Issue by pke** [padrino/padrino-framework#749]
In 0.10.5 it's not possible to only change the password without changing any of the other properties.
Calling a.password = "test" will not make the account dirty and therefore a a.save does not update the model in the database. Setting a.name and then calling a.save will update the model correctly.

**Comment by cshimvin** [comment]
It seems that the issue is still reoccurring on our version of Padrino (v.0.12.2). The password seems like it updates (by update confirmation) when a new password is entered but it doesn't update the database.

However, when updating one of the other fields as well the password, the passwordupdates successfully.

Can this be reopened?

**Comment by ujifgc** [comment]
Fixed for DataMapper, checked for ActiveRecord, Sequel, MongoMapper.
