### ISSUE TITLE
link_to with block in slim doesn't seem to work

### ISSUE THREAD

**Issue by simonc** [padrino/padrino-framework#777]
I am using slim as my template syntax and using a block with the `link_to` helper doesn't work.

My test is like this:

``` slim
== link_to("/") do
  span Hello
```

It doesn't print anything.

I digged into the code and traced it back to `SlimHandler.concat_to_template`:

``` ruby
def concat_to_template(text="")
  self.output_buffer << text if is_type? && text
  nil
end
```

It doesn't come from the condition, I commented it and it didn't change anything.

**Comment by rafaelgonzalez** [comment]
@pencilcheck and @akiva 

Not sure if you figured this out by now, but I was trying to do something like:

```ruby
li
  = link_to channel.name, channel_path(channel) do
    figure
      img src="//placekitten.com/g/400/200"
    h3
      = channel.name
    p
      = channel.description
```

This didn't work. This is because I'm trying to set the content of the link with the first argument of `link_to`, when of course the content of the block is doing that.

Once you remove that first argument: `= link_to channel_path(channel) do` it works!

**Comment by jarthod** [comment]
Not sure if it helps but I recently switched to `slim` and got a similar issue, where:

```
= link_to new_user_session_path do
  | sign in
```

Would render the whole page template again instead of just the link and found the reason to be streaming. I'm using `render stream: true` and if I simply render the page without streaming the `link_to` with block is working as expected.

With streaming enabled it seems slim renders the block first (I got the content of the link outside, before it) and then renders the link with the whole template inside. So you may want to have a look at this in stream mode ;)

**Comment by bkunzi01** [comment]
I also cannot get link_to blocks such as 
      `= link_to some_path_here do`
          | Some html here
To work.  Inline links such as: `link_to "LinkName", some_path, data: {whatever: 'works'}` work!

**Comment by canjoku** [comment]
you can pass content as a block [in this case Home. It does'nt have to be string either]
<%=  link_to(route_path(:id)) do %>
    'Home'
<% end %>
  Outputs => <a href="/">Home</a>
